#mysql data image
mysql_data:
  image: docker.io/busybox:latest
  volumes:
  - ./mysql_data:/var/lib/mysql

#mysql program image
mysql_server:
  image: docker.io/mysql:latest
  volumes_from:
  - mysql_data
  environment:
  - MYSQL_ROOT_PASSWORD=DROWSSAP

#mongodb data image
mongodb_data:
  image: docker.io/busybox:latest
  volumes:
  - ./mongodb_data:/data/db

#mongodb program image
mongodb_server:
  image: docker.io/mongo:latest
  volumes_from:
  - mongodb_data

#php file image
www_php: 
  image: docker.io/busybox:latest
  volumes:
  - ./www_php:/var/www/html

#php program image
php_fpm:
  #build: ./build/php
  image: gzlock/php-with-mongodb:latest
  volumes_from:
  - www_php
  links:
  - mysql_server:mysql
  - mongodb_server:mongodb

#nodejs file image
www_nodejs: 
  image: docker.io/busybox:latest
  volumes:
  - ./www_nodejs:/usr/src/myapp/host

#nodejs program image
nodejs:
  #build: ./build/nodejs
  image: gzlock/node-with-mongoose:latest
  volumes_from:
  - www_nodejs
  restart: always
  command: "node /usr/src/myapp/app.js"
  links:
  - mysql_server:mysql
  - mongodb_server:mongodb

#node-with-mongo-express image
mongo_express:
  #build: ./build/mongo-express
  image: gzlock/node-with-mongoexpress:latest
  restart: always
  links:
  - mongodb_server:mongo

#nginx programe image
nginx:
  image: docker.io/nginx:latest
  volumes:
  - ./nginx_conf:/etc/nginx/conf.d
  volumes_from:
  - www_php
  links:
  # port 9000
  - php_fpm:php
  # port 8080
  - nodejs
  # port 8081
  - mongo_express
  ports:
  - "80:80"