#mysql data image
mysql_data:
  image: docker.io/busybox:latest
  volumes:
  - ./mysql_data:/var/lib/mysql
  - ./backup/mysql:/backup

#mysql program image
mysql_server:
  image: docker.io/mysql:latest
  volumes_from:
  - mysql_data
  environment:
  - MYSQL_ROOT_PASSWORD=DROWSSAP
  log_driver: "none"

#mongodb data image
mongodb_data:
  image: docker.io/busybox:latest
  volumes:
  - ./mongodb_data:/data/db
  - ./backup/mongodb:/backup

#mongodb program image
mongodb_server:
  image: docker.io/mongo:latest
  volumes_from:
  - mongodb_data
  log_driver: "none"

#php file image
www_php: 
  image: docker.io/busybox:latest
  volumes:
  - ./www_php:/var/www/html

#php program image
php_fpm:
  #build: ./build/php
  image: gzlock/php-with-mongodb:latest
  volumes_from:
  - www_php
  links:
  - mysql_server:mysql
  - mongodb_server:mongodb
  log_driver: "none"

#nodejs file image
www_nodejs: 
  image: docker.io/busybox:latest
  volumes:
  - ./www_nodejs:/usr/src/myapp/host

#nodejs program image
nodejs:
  #build: ./build/nodejs
  image: gzlock/node-base-image:latest
  volumes_from:
  - www_nodejs
  restart: always
  command: "node /usr/src/myapp/app.js"
  links:
  - mysql_server:mysql
  - mongodb_server:mongodb

#node-with-mongo-express image
mongo_express:
  image: gzlock/node-with-mongo-express:latest
  restart: always
  links:
  - mongodb_server:mongodb
  ports:
  - "8081:8081"
  log_driver: "none"

#nginx programe image
nginx:
  image: docker.io/gzlock/nginx:latest
  volumes:
  - ./nginx_conf:/etc/nginx/conf.d
  volumes_from:
  - www_php
  links:
  # port 9000
  - php_fpm:php
  # port 8080
  - nodejs
  ports:
  - "80:80"
  log_driver: "none"
