#mysql data image
mysql_data:
  image: docker.io/busybox:latest
  volumes:
  - ./mysql_data:/var/lib/mysql

#mysql program image
mysql_server:
  image: docker.io/mysql:latest
  volumes_from:
  - mysql_data
  environment:
  - MYSQL_ROOT_PASSWORD=DROWSSAP

#mongodb data image
mongodb_data:
  image: docker.io/busybox:latest
  volumes:
  - ./mongodb_data:/data/db

#mongodb program image
mongodb_server:
  image: docker.io/mongo:latest
  volumes_from:
  - mongodb_data

#php file image
www_php: 
  image: docker.io/busybox:latest
  volumes:
  - ./www_php:/var/www/html

#php program image
php_fpm:
  build: ./build/php
  volumes_from:
  - www_php
  links:
  - mysql_server:mysql
  - mongodb_server:mongodb

#nodejs file image
www_nodejs: 
  image: docker.io/busybox:latest
  volumes:
  - ./www_nodejs:/usr/src/myapp

#nodejs program image
nodejs:
  build: ./build/nodejs
  image: q84629462/node-with-supervisor:latest
  volumes_from:
  - www_nodejs
  command: "node /usr/src/myapp/index.js"

#nginx programe image
nginx:
  image: docker.io/nginx:latest
  volumes:
  - ./nginx_conf:/etc/nginx/conf.d
  volumes_from:
  - www_php
  #Not required
  #- www_nodejs 
  links:
  - php_fpm:php
  - nodejs
  ports:
  - "80:80"